export default [
  `Feijão`,
  `Arroz`,
  `Macarrão`,
  `Café`,
  `Açúcar`,
  `Cuscuz`,
  `Farinha`,
  `Leite em caixa`,
  `Leite em pó`,
  `Cerveja`,
  `Calabresa`,
  `Sabão em barra`,
  `Sabão em pó`,
  `Água sanitária`,
  `Detergente`,
  `Pasta de dentes`,
  `Escova de destes`,
  `Fraldas`,
  `Papel Higiênico`,
  `Peito de frango`,
  `Bife de boi`,
  `Bisteca de boi`,
  `Bisteca de porco`,
  `Coxas sobre coxas`,
  `Queijo`,
  `Salsicha`,
  `Salame`,
  `Morta dela`,
  `Melancia`,
  `Goiaba`,
  `Abacaxi`,
] as string[];
